### ISSUE TITLE
希望实现的功能/建议

### ISSUE THREAD

**Issue by chasiopen** [inrhor/QuestEngine#1]
1.希望能够对目前市面上的主流RPG插件提供支持
比如MythicMobs的怪物击杀，MMOcore的职业限制，MMOitems的物品支持等。
2.希望能有较好的多人合作任务的支持
例如对组队插件Parties的支持，希望能实现这样的场景：
可以利用组队插件共同击杀多少只MythicMobs生物（进度共享）
可以利用组队插件共同击杀一只超级生物（一人击杀，全队的其他成员能够参与击杀）
在使用组队插件时小队的奖励可以平摊或者自由分配/roll点获得之类的
3.希望有良好的GUI面板，完善的本地化语言支持。

万分感谢，十分期待！

**Comment by inrhor** [comment]
1.主流插件的支持会有的，计划方向倾向通过附属进行挂钩
2.3.早已在计划之中

感谢支持

**Comment by inrhor** [comment]
3.Gui面板功能于 3.1.0 版本实现
